import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import React from "react";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "../auth";
// import AuthProvider from "@/providers/AuthProvider";


const roboto = Roboto({
  display: 'swap', subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  // session: any
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>

      <html lang="en">
        <body className={roboto.className} style={{ backgroundColor: '#000000' }}>
          {/* <AuthProvider session={session}> */}
          <Toaster position="top-center"/>
            {children}
          {/* </AuthProvider> */}
          <div id="root_modal" />
        </body>
      </html>
    </SessionProvider>
  );
}
