import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import React from "react";
import { Toaster } from "react-hot-toast";
import "./globals.css";

import { getServerSession } from "next-auth";
import SessionWrapper from "@/app/providers/SessionWrapper";
import { authOptions } from "@/auth";


const roboto = Roboto({
  display: 'swap', subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  // session: any
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={roboto.className} style={{ backgroundColor: '#000000' }}>
        <Toaster position="top-center" />
        <SessionWrapper session={session}>
          {children}
        </SessionWrapper>
        <div id="root_modal" />
      </body>
    </html>
  );
}
